# Find all materials here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# /craftreload to reload config.
messages:
  blockedmessage: "&cCrafting this item is blocked."
  chatmessage: "&cYou can't craft that"
chatmessage-enabled: false
blocked:
  - 'STICK'